server:
  address: ":8088"
  env: "development"

database:
  url: "postgresql://postgres:postgres@localhost:5432/akza?sslmode=disable"

jwt:
  secret: "akza-super-secret"
  expires_hours: 12

logger:
  level: "development"

s3:
  bucket: "akza-media"
  endpoint: "https://storage.yandexcloud.net"
  cdn_base: "https://cdn.akza.store"
  cdn_token: "d28eaa1a3044bc11f21339c4dfb42a7b"
  region: "ru-central1"
  access_key: "YCAJEbr8dMkZidI94oWorUDal"
  secret_key: "YCNZsdis3VK2D2pU6fWB7VMxp6r4LeWJXWDv1_YX"

telegram:
  bot_token: "8222663561:AAHHDWX4Cck0-eSJY9TvTbNVBkT1aUCZA_Y"
  admin_chat_id: "5394497479"

cors:
  allowed_origins:
    - "http://localhost:5173"
    - "http://localhost:5174"
    - "https://akza.store"
    - "https://admin.akza.store"
